version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433
  web:
    build: .
    command: python server.py -dev
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    expose: 
      - "8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
